// 指定的当前proto语法的版本，有2和3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: cloud_disk.proto

// 指定文件生成出来的package

package cloud_disk

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CloudDiskConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumeType string `protobuf:"bytes,1,opt,name=volume_type,json=volumeType,proto3" json:"volume_type,omitempty"`
	SizeInG    int32  `protobuf:"varint,2,opt,name=size_in_g,json=sizeInG,proto3" json:"size_in_g,omitempty"`
}

func (x *CloudDiskConf) Reset() {
	*x = CloudDiskConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudDiskConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudDiskConf) ProtoMessage() {}

func (x *CloudDiskConf) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudDiskConf.ProtoReflect.Descriptor instead.
func (*CloudDiskConf) Descriptor() ([]byte, []int) {
	return file_cloud_disk_proto_rawDescGZIP(), []int{0}
}

func (x *CloudDiskConf) GetVolumeType() string {
	if x != nil {
		return x.VolumeType
	}
	return ""
}

func (x *CloudDiskConf) GetSizeInG() int32 {
	if x != nil {
		return x.SizeInG
	}
	return 0
}

type CloudDisk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumeId             string         `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	VolumeName           string         `protobuf:"bytes,2,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	VolumeDesc           string         `protobuf:"bytes,3,opt,name=volume_desc,json=volumeDesc,proto3" json:"volume_desc,omitempty"`
	Region               string         `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	AvailabilityZone     string         `protobuf:"bytes,5,opt,name=availability_zone,json=availabilityZone,proto3" json:"availability_zone,omitempty"`
	CloudDiskConf        *CloudDiskConf `protobuf:"bytes,6,opt,name=cloud_disk_conf,json=cloudDiskConf,proto3" json:"cloud_disk_conf,omitempty"`
	VolumeStatus         string         `protobuf:"bytes,7,opt,name=volume_status,json=volumeStatus,proto3" json:"volume_status,omitempty"`
	CreatedTime          string         `protobuf:"bytes,8,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime          string         `protobuf:"bytes,9,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	AttachInstanceId     string         `protobuf:"bytes,10,opt,name=attach_instance_id,json=attachInstanceId,proto3" json:"attach_instance_id,omitempty"`
	AttachInstanceDevice string         `protobuf:"bytes,11,opt,name=attach_instance_device,json=attachInstanceDevice,proto3" json:"attach_instance_device,omitempty"`
	AttachedTime         string         `protobuf:"bytes,12,opt,name=attached_time,json=attachedTime,proto3" json:"attached_time,omitempty"`
}

func (x *CloudDisk) Reset() {
	*x = CloudDisk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudDisk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudDisk) ProtoMessage() {}

func (x *CloudDisk) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudDisk.ProtoReflect.Descriptor instead.
func (*CloudDisk) Descriptor() ([]byte, []int) {
	return file_cloud_disk_proto_rawDescGZIP(), []int{1}
}

func (x *CloudDisk) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *CloudDisk) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *CloudDisk) GetVolumeDesc() string {
	if x != nil {
		return x.VolumeDesc
	}
	return ""
}

func (x *CloudDisk) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CloudDisk) GetAvailabilityZone() string {
	if x != nil {
		return x.AvailabilityZone
	}
	return ""
}

func (x *CloudDisk) GetCloudDiskConf() *CloudDiskConf {
	if x != nil {
		return x.CloudDiskConf
	}
	return nil
}

func (x *CloudDisk) GetVolumeStatus() string {
	if x != nil {
		return x.VolumeStatus
	}
	return ""
}

func (x *CloudDisk) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *CloudDisk) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *CloudDisk) GetAttachInstanceId() string {
	if x != nil {
		return x.AttachInstanceId
	}
	return ""
}

func (x *CloudDisk) GetAttachInstanceDevice() string {
	if x != nil {
		return x.AttachInstanceDevice
	}
	return ""
}

func (x *CloudDisk) GetAttachedTime() string {
	if x != nil {
		return x.AttachedTime
	}
	return ""
}

type CreateCloudDiskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apikey           string         `protobuf:"bytes,1,opt,name=apikey,proto3" json:"apikey,omitempty"`
	TenantId         string         `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PlatformUserid   string         `protobuf:"bytes,3,opt,name=platform_userid,json=platformUserid,proto3" json:"platform_userid,omitempty"`
	VolumeName       string         `protobuf:"bytes,4,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	VolumeDesc       string         `protobuf:"bytes,5,opt,name=volume_desc,json=volumeDesc,proto3" json:"volume_desc,omitempty"`
	Region           string         `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	AvailabilityZone string         `protobuf:"bytes,7,opt,name=availability_zone,json=availabilityZone,proto3" json:"availability_zone,omitempty"`
	CloudDiskConf    *CloudDiskConf `protobuf:"bytes,8,opt,name=cloud_disk_conf,json=cloudDiskConf,proto3" json:"cloud_disk_conf,omitempty"`
}

func (x *CreateCloudDiskReq) Reset() {
	*x = CreateCloudDiskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCloudDiskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCloudDiskReq) ProtoMessage() {}

func (x *CreateCloudDiskReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCloudDiskReq.ProtoReflect.Descriptor instead.
func (*CreateCloudDiskReq) Descriptor() ([]byte, []int) {
	return file_cloud_disk_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCloudDiskReq) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *CreateCloudDiskReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateCloudDiskReq) GetPlatformUserid() string {
	if x != nil {
		return x.PlatformUserid
	}
	return ""
}

func (x *CreateCloudDiskReq) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *CreateCloudDiskReq) GetVolumeDesc() string {
	if x != nil {
		return x.VolumeDesc
	}
	return ""
}

func (x *CreateCloudDiskReq) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateCloudDiskReq) GetAvailabilityZone() string {
	if x != nil {
		return x.AvailabilityZone
	}
	return ""
}

func (x *CreateCloudDiskReq) GetCloudDiskConf() *CloudDiskConf {
	if x != nil {
		return x.CloudDiskConf
	}
	return nil
}

type GetCloudDiskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apikey         string `protobuf:"bytes,1,opt,name=apikey,proto3" json:"apikey,omitempty"`
	TenantId       string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PlatformUserid string `protobuf:"bytes,3,opt,name=platform_userid,json=platformUserid,proto3" json:"platform_userid,omitempty"`
	VolumeId       string `protobuf:"bytes,4,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
}

func (x *GetCloudDiskReq) Reset() {
	*x = GetCloudDiskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCloudDiskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudDiskReq) ProtoMessage() {}

func (x *GetCloudDiskReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudDiskReq.ProtoReflect.Descriptor instead.
func (*GetCloudDiskReq) Descriptor() ([]byte, []int) {
	return file_cloud_disk_proto_rawDescGZIP(), []int{3}
}

func (x *GetCloudDiskReq) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *GetCloudDiskReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetCloudDiskReq) GetPlatformUserid() string {
	if x != nil {
		return x.PlatformUserid
	}
	return ""
}

func (x *GetCloudDiskReq) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type ReqizeCloudDiskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apikey         string         `protobuf:"bytes,1,opt,name=apikey,proto3" json:"apikey,omitempty"`
	TenantId       string         `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PlatformUserid string         `protobuf:"bytes,3,opt,name=platform_userid,json=platformUserid,proto3" json:"platform_userid,omitempty"`
	VolumeId       string         `protobuf:"bytes,4,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	CloudDiskConf  *CloudDiskConf `protobuf:"bytes,5,opt,name=cloud_disk_conf,json=cloudDiskConf,proto3" json:"cloud_disk_conf,omitempty"`
}

func (x *ReqizeCloudDiskReq) Reset() {
	*x = ReqizeCloudDiskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqizeCloudDiskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqizeCloudDiskReq) ProtoMessage() {}

func (x *ReqizeCloudDiskReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqizeCloudDiskReq.ProtoReflect.Descriptor instead.
func (*ReqizeCloudDiskReq) Descriptor() ([]byte, []int) {
	return file_cloud_disk_proto_rawDescGZIP(), []int{4}
}

func (x *ReqizeCloudDiskReq) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *ReqizeCloudDiskReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReqizeCloudDiskReq) GetPlatformUserid() string {
	if x != nil {
		return x.PlatformUserid
	}
	return ""
}

func (x *ReqizeCloudDiskReq) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *ReqizeCloudDiskReq) GetCloudDiskConf() *CloudDiskConf {
	if x != nil {
		return x.CloudDiskConf
	}
	return nil
}

type ModifyCloudDiskInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apikey         string `protobuf:"bytes,1,opt,name=apikey,proto3" json:"apikey,omitempty"`
	TenantId       string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PlatformUserid string `protobuf:"bytes,3,opt,name=platform_userid,json=platformUserid,proto3" json:"platform_userid,omitempty"`
	VolumeId       string `protobuf:"bytes,4,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	VolumeName     string `protobuf:"bytes,5,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	VolumeDesc     string `protobuf:"bytes,6,opt,name=volume_desc,json=volumeDesc,proto3" json:"volume_desc,omitempty"`
}

func (x *ModifyCloudDiskInfoReq) Reset() {
	*x = ModifyCloudDiskInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyCloudDiskInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyCloudDiskInfoReq) ProtoMessage() {}

func (x *ModifyCloudDiskInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyCloudDiskInfoReq.ProtoReflect.Descriptor instead.
func (*ModifyCloudDiskInfoReq) Descriptor() ([]byte, []int) {
	return file_cloud_disk_proto_rawDescGZIP(), []int{5}
}

func (x *ModifyCloudDiskInfoReq) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *ModifyCloudDiskInfoReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ModifyCloudDiskInfoReq) GetPlatformUserid() string {
	if x != nil {
		return x.PlatformUserid
	}
	return ""
}

func (x *ModifyCloudDiskInfoReq) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *ModifyCloudDiskInfoReq) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *ModifyCloudDiskInfoReq) GetVolumeDesc() string {
	if x != nil {
		return x.VolumeDesc
	}
	return ""
}

type OperateCloudDiskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apikey         string `protobuf:"bytes,1,opt,name=apikey,proto3" json:"apikey,omitempty"`
	TenantId       string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PlatformUserid string `protobuf:"bytes,3,opt,name=platform_userid,json=platformUserid,proto3" json:"platform_userid,omitempty"`
	VolumeId       string `protobuf:"bytes,4,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	InstanceId     string `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	OpsType        string `protobuf:"bytes,6,opt,name=ops_type,json=opsType,proto3" json:"ops_type,omitempty"` //attach or detach
}

func (x *OperateCloudDiskReq) Reset() {
	*x = OperateCloudDiskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateCloudDiskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateCloudDiskReq) ProtoMessage() {}

func (x *OperateCloudDiskReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateCloudDiskReq.ProtoReflect.Descriptor instead.
func (*OperateCloudDiskReq) Descriptor() ([]byte, []int) {
	return file_cloud_disk_proto_rawDescGZIP(), []int{6}
}

func (x *OperateCloudDiskReq) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *OperateCloudDiskReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *OperateCloudDiskReq) GetPlatformUserid() string {
	if x != nil {
		return x.PlatformUserid
	}
	return ""
}

func (x *OperateCloudDiskReq) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *OperateCloudDiskReq) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *OperateCloudDiskReq) GetOpsType() string {
	if x != nil {
		return x.OpsType
	}
	return ""
}

type DeleteCloudDiskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apikey         string `protobuf:"bytes,1,opt,name=apikey,proto3" json:"apikey,omitempty"`
	TenantId       string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PlatformUserid string `protobuf:"bytes,3,opt,name=platform_userid,json=platformUserid,proto3" json:"platform_userid,omitempty"`
	VolumeId       string `protobuf:"bytes,4,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
}

func (x *DeleteCloudDiskReq) Reset() {
	*x = DeleteCloudDiskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCloudDiskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCloudDiskReq) ProtoMessage() {}

func (x *DeleteCloudDiskReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCloudDiskReq.ProtoReflect.Descriptor instead.
func (*DeleteCloudDiskReq) Descriptor() ([]byte, []int) {
	return file_cloud_disk_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCloudDiskReq) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *DeleteCloudDiskReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteCloudDiskReq) GetPlatformUserid() string {
	if x != nil {
		return x.PlatformUserid
	}
	return ""
}

func (x *DeleteCloudDiskReq) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type DeleteCloudDiskRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumeId    string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	DeletedTime string `protobuf:"bytes,2,opt,name=deleted_time,json=deletedTime,proto3" json:"deleted_time,omitempty"`
}

func (x *DeleteCloudDiskRes) Reset() {
	*x = DeleteCloudDiskRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCloudDiskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCloudDiskRes) ProtoMessage() {}

func (x *DeleteCloudDiskRes) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCloudDiskRes.ProtoReflect.Descriptor instead.
func (*DeleteCloudDiskRes) Descriptor() ([]byte, []int) {
	return file_cloud_disk_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCloudDiskRes) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *DeleteCloudDiskRes) GetDeletedTime() string {
	if x != nil {
		return x.DeletedTime
	}
	return ""
}

var File_cloud_disk_proto protoreflect.FileDescriptor

var file_cloud_disk_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x22, 0x4c,
	0x0a, 0x0d, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x12,
	0x1f, 0x0a, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x69, 0x6e, 0x5f, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x69, 0x7a, 0x65, 0x49, 0x6e, 0x47, 0x22, 0xe6, 0x03, 0x0a,
	0x09, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x44, 0x65, 0x73, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x12, 0x2b, 0x0a, 0x11, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x5f, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x41,
	0x0a, 0x0f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f,
	0x64, 0x69, 0x73, 0x6b, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x6f,
	0x6e, 0x66, 0x52, 0x0d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x6f, 0x6e,
	0x66, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12,
	0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x16, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xbc, 0x02, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70,
	0x69, 0x6b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x44, 0x65, 0x73, 0x63, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x11, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x5f, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5a, 0x6f, 0x6e,
	0x65, 0x12, 0x41, 0x0a, 0x0f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73,
	0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x0d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b,
	0x43, 0x6f, 0x6e, 0x66, 0x22, 0x8c, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a,
	0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x49, 0x64, 0x22, 0xd2, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x69, 0x7a, 0x65, 0x43, 0x6c,
	0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70,
	0x69, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x6b,
	0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x27, 0x0a, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x0f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64,
	0x69, 0x73, 0x6b, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x2e, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x0d, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x44, 0x69, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x22, 0xd5, 0x01, 0x0a, 0x16, 0x4d, 0x6f, 0x64,
	0x69, 0x66, 0x79, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x44, 0x65, 0x73, 0x63,
	0x22, 0xcc, 0x01, 0x0a, 0x13, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a,
	0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x70, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x8f, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44,
	0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x73,
	0x65, 0x72, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49,
	0x64, 0x22, 0x54, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x44, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x32, 0xdb, 0x03, 0x0a, 0x10, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x44, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x12,
	0x1e, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a,
	0x15, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x2e, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x42, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x1b, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64,
	0x69, 0x73, 0x6b, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b,
	0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b,
	0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x48, 0x0a, 0x0f, 0x52, 0x65,
	0x71, 0x69, 0x7a, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x1e, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x2e, 0x52, 0x65, 0x71, 0x69, 0x7a,
	0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x44, 0x69, 0x73, 0x6b, 0x12, 0x50, 0x0a, 0x13, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x43, 0x6c,
	0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x43,
	0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x15, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x2e, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x4a, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x1f, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43,
	0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69,
	0x73, 0x6b, 0x12, 0x51, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x1e, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69,
	0x73, 0x6b, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69,
	0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x64, 0x69,
	0x73, 0x6b, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x69,
	0x73, 0x6b, 0x52, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cloud_disk_proto_rawDescOnce sync.Once
	file_cloud_disk_proto_rawDescData = file_cloud_disk_proto_rawDesc
)

func file_cloud_disk_proto_rawDescGZIP() []byte {
	file_cloud_disk_proto_rawDescOnce.Do(func() {
		file_cloud_disk_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_disk_proto_rawDescData)
	})
	return file_cloud_disk_proto_rawDescData
}

var file_cloud_disk_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cloud_disk_proto_goTypes = []interface{}{
	(*CloudDiskConf)(nil),          // 0: cloud_disk.CloudDiskConf
	(*CloudDisk)(nil),              // 1: cloud_disk.CloudDisk
	(*CreateCloudDiskReq)(nil),     // 2: cloud_disk.CreateCloudDiskReq
	(*GetCloudDiskReq)(nil),        // 3: cloud_disk.GetCloudDiskReq
	(*ReqizeCloudDiskReq)(nil),     // 4: cloud_disk.ReqizeCloudDiskReq
	(*ModifyCloudDiskInfoReq)(nil), // 5: cloud_disk.ModifyCloudDiskInfoReq
	(*OperateCloudDiskReq)(nil),    // 6: cloud_disk.OperateCloudDiskReq
	(*DeleteCloudDiskReq)(nil),     // 7: cloud_disk.DeleteCloudDiskReq
	(*DeleteCloudDiskRes)(nil),     // 8: cloud_disk.DeleteCloudDiskRes
}
var file_cloud_disk_proto_depIdxs = []int32{
	0, // 0: cloud_disk.CloudDisk.cloud_disk_conf:type_name -> cloud_disk.CloudDiskConf
	0, // 1: cloud_disk.CreateCloudDiskReq.cloud_disk_conf:type_name -> cloud_disk.CloudDiskConf
	0, // 2: cloud_disk.ReqizeCloudDiskReq.cloud_disk_conf:type_name -> cloud_disk.CloudDiskConf
	2, // 3: cloud_disk.CloudDiskService.CreateCloudDisk:input_type -> cloud_disk.CreateCloudDiskReq
	3, // 4: cloud_disk.CloudDiskService.GetCloudDisk:input_type -> cloud_disk.GetCloudDiskReq
	4, // 5: cloud_disk.CloudDiskService.ReqizeCloudDisk:input_type -> cloud_disk.ReqizeCloudDiskReq
	5, // 6: cloud_disk.CloudDiskService.ModifyCloudDiskInfo:input_type -> cloud_disk.ModifyCloudDiskInfoReq
	6, // 7: cloud_disk.CloudDiskService.OperateCloudDisk:input_type -> cloud_disk.OperateCloudDiskReq
	7, // 8: cloud_disk.CloudDiskService.DeleteCloudDisk:input_type -> cloud_disk.DeleteCloudDiskReq
	1, // 9: cloud_disk.CloudDiskService.CreateCloudDisk:output_type -> cloud_disk.CloudDisk
	1, // 10: cloud_disk.CloudDiskService.GetCloudDisk:output_type -> cloud_disk.CloudDisk
	1, // 11: cloud_disk.CloudDiskService.ReqizeCloudDisk:output_type -> cloud_disk.CloudDisk
	1, // 12: cloud_disk.CloudDiskService.ModifyCloudDiskInfo:output_type -> cloud_disk.CloudDisk
	1, // 13: cloud_disk.CloudDiskService.OperateCloudDisk:output_type -> cloud_disk.CloudDisk
	8, // 14: cloud_disk.CloudDiskService.DeleteCloudDisk:output_type -> cloud_disk.DeleteCloudDiskRes
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cloud_disk_proto_init() }
func file_cloud_disk_proto_init() {
	if File_cloud_disk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cloud_disk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudDiskConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_disk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudDisk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_disk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCloudDiskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_disk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCloudDiskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_disk_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqizeCloudDiskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_disk_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyCloudDiskInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_disk_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateCloudDiskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_disk_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCloudDiskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_disk_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCloudDiskRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_disk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloud_disk_proto_goTypes,
		DependencyIndexes: file_cloud_disk_proto_depIdxs,
		MessageInfos:      file_cloud_disk_proto_msgTypes,
	}.Build()
	File_cloud_disk_proto = out.File
	file_cloud_disk_proto_rawDesc = nil
	file_cloud_disk_proto_goTypes = nil
	file_cloud_disk_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CloudDiskServiceClient is the client API for CloudDiskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CloudDiskServiceClient interface {
	//创建云硬盘
	CreateCloudDisk(ctx context.Context, in *CreateCloudDiskReq, opts ...grpc.CallOption) (*CloudDisk, error)
	//获取云硬盘信息
	GetCloudDisk(ctx context.Context, in *GetCloudDiskReq, opts ...grpc.CallOption) (*CloudDisk, error)
	//云硬盘扩容
	ReqizeCloudDisk(ctx context.Context, in *ReqizeCloudDiskReq, opts ...grpc.CallOption) (*CloudDisk, error)
	//修改云硬盘信息
	ModifyCloudDiskInfo(ctx context.Context, in *ModifyCloudDiskInfoReq, opts ...grpc.CallOption) (*CloudDisk, error)
	//云主机挂载/卸载云硬盘
	OperateCloudDisk(ctx context.Context, in *OperateCloudDiskReq, opts ...grpc.CallOption) (*CloudDisk, error)
	//删除云硬盘
	DeleteCloudDisk(ctx context.Context, in *DeleteCloudDiskReq, opts ...grpc.CallOption) (*DeleteCloudDiskRes, error)
}

type cloudDiskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudDiskServiceClient(cc grpc.ClientConnInterface) CloudDiskServiceClient {
	return &cloudDiskServiceClient{cc}
}

func (c *cloudDiskServiceClient) CreateCloudDisk(ctx context.Context, in *CreateCloudDiskReq, opts ...grpc.CallOption) (*CloudDisk, error) {
	out := new(CloudDisk)
	err := c.cc.Invoke(ctx, "/cloud_disk.CloudDiskService/CreateCloudDisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDiskServiceClient) GetCloudDisk(ctx context.Context, in *GetCloudDiskReq, opts ...grpc.CallOption) (*CloudDisk, error) {
	out := new(CloudDisk)
	err := c.cc.Invoke(ctx, "/cloud_disk.CloudDiskService/GetCloudDisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDiskServiceClient) ReqizeCloudDisk(ctx context.Context, in *ReqizeCloudDiskReq, opts ...grpc.CallOption) (*CloudDisk, error) {
	out := new(CloudDisk)
	err := c.cc.Invoke(ctx, "/cloud_disk.CloudDiskService/ReqizeCloudDisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDiskServiceClient) ModifyCloudDiskInfo(ctx context.Context, in *ModifyCloudDiskInfoReq, opts ...grpc.CallOption) (*CloudDisk, error) {
	out := new(CloudDisk)
	err := c.cc.Invoke(ctx, "/cloud_disk.CloudDiskService/ModifyCloudDiskInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDiskServiceClient) OperateCloudDisk(ctx context.Context, in *OperateCloudDiskReq, opts ...grpc.CallOption) (*CloudDisk, error) {
	out := new(CloudDisk)
	err := c.cc.Invoke(ctx, "/cloud_disk.CloudDiskService/OperateCloudDisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDiskServiceClient) DeleteCloudDisk(ctx context.Context, in *DeleteCloudDiskReq, opts ...grpc.CallOption) (*DeleteCloudDiskRes, error) {
	out := new(DeleteCloudDiskRes)
	err := c.cc.Invoke(ctx, "/cloud_disk.CloudDiskService/DeleteCloudDisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudDiskServiceServer is the server API for CloudDiskService service.
type CloudDiskServiceServer interface {
	//创建云硬盘
	CreateCloudDisk(context.Context, *CreateCloudDiskReq) (*CloudDisk, error)
	//获取云硬盘信息
	GetCloudDisk(context.Context, *GetCloudDiskReq) (*CloudDisk, error)
	//云硬盘扩容
	ReqizeCloudDisk(context.Context, *ReqizeCloudDiskReq) (*CloudDisk, error)
	//修改云硬盘信息
	ModifyCloudDiskInfo(context.Context, *ModifyCloudDiskInfoReq) (*CloudDisk, error)
	//云主机挂载/卸载云硬盘
	OperateCloudDisk(context.Context, *OperateCloudDiskReq) (*CloudDisk, error)
	//删除云硬盘
	DeleteCloudDisk(context.Context, *DeleteCloudDiskReq) (*DeleteCloudDiskRes, error)
}

// UnimplementedCloudDiskServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCloudDiskServiceServer struct {
}

func (*UnimplementedCloudDiskServiceServer) CreateCloudDisk(context.Context, *CreateCloudDiskReq) (*CloudDisk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCloudDisk not implemented")
}
func (*UnimplementedCloudDiskServiceServer) GetCloudDisk(context.Context, *GetCloudDiskReq) (*CloudDisk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCloudDisk not implemented")
}
func (*UnimplementedCloudDiskServiceServer) ReqizeCloudDisk(context.Context, *ReqizeCloudDiskReq) (*CloudDisk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqizeCloudDisk not implemented")
}
func (*UnimplementedCloudDiskServiceServer) ModifyCloudDiskInfo(context.Context, *ModifyCloudDiskInfoReq) (*CloudDisk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyCloudDiskInfo not implemented")
}
func (*UnimplementedCloudDiskServiceServer) OperateCloudDisk(context.Context, *OperateCloudDiskReq) (*CloudDisk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OperateCloudDisk not implemented")
}
func (*UnimplementedCloudDiskServiceServer) DeleteCloudDisk(context.Context, *DeleteCloudDiskReq) (*DeleteCloudDiskRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCloudDisk not implemented")
}

func RegisterCloudDiskServiceServer(s *grpc.Server, srv CloudDiskServiceServer) {
	s.RegisterService(&_CloudDiskService_serviceDesc, srv)
}

func _CloudDiskService_CreateCloudDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCloudDiskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDiskServiceServer).CreateCloudDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_disk.CloudDiskService/CreateCloudDisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDiskServiceServer).CreateCloudDisk(ctx, req.(*CreateCloudDiskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDiskService_GetCloudDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCloudDiskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDiskServiceServer).GetCloudDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_disk.CloudDiskService/GetCloudDisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDiskServiceServer).GetCloudDisk(ctx, req.(*GetCloudDiskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDiskService_ReqizeCloudDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqizeCloudDiskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDiskServiceServer).ReqizeCloudDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_disk.CloudDiskService/ReqizeCloudDisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDiskServiceServer).ReqizeCloudDisk(ctx, req.(*ReqizeCloudDiskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDiskService_ModifyCloudDiskInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyCloudDiskInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDiskServiceServer).ModifyCloudDiskInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_disk.CloudDiskService/ModifyCloudDiskInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDiskServiceServer).ModifyCloudDiskInfo(ctx, req.(*ModifyCloudDiskInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDiskService_OperateCloudDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperateCloudDiskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDiskServiceServer).OperateCloudDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_disk.CloudDiskService/OperateCloudDisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDiskServiceServer).OperateCloudDisk(ctx, req.(*OperateCloudDiskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDiskService_DeleteCloudDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCloudDiskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDiskServiceServer).DeleteCloudDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_disk.CloudDiskService/DeleteCloudDisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDiskServiceServer).DeleteCloudDisk(ctx, req.(*DeleteCloudDiskReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CloudDiskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud_disk.CloudDiskService",
	HandlerType: (*CloudDiskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCloudDisk",
			Handler:    _CloudDiskService_CreateCloudDisk_Handler,
		},
		{
			MethodName: "GetCloudDisk",
			Handler:    _CloudDiskService_GetCloudDisk_Handler,
		},
		{
			MethodName: "ReqizeCloudDisk",
			Handler:    _CloudDiskService_ReqizeCloudDisk_Handler,
		},
		{
			MethodName: "ModifyCloudDiskInfo",
			Handler:    _CloudDiskService_ModifyCloudDiskInfo_Handler,
		},
		{
			MethodName: "OperateCloudDisk",
			Handler:    _CloudDiskService_OperateCloudDisk_Handler,
		},
		{
			MethodName: "DeleteCloudDisk",
			Handler:    _CloudDiskService_DeleteCloudDisk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloud_disk.proto",
}
